name: monenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - ipykernel==6.13.0
  - jupyter==1.0.0
  - matplotlib==3.5.1
  - nbconvert==6.5.0
  - nbclient==0.6.0
  - nbformat==5.3.0
  - pandas==1.4.1
  - PyYAML==6.0
  - s3fs==2022.2.0
  - scikit-learn==1.0.2
  - seaborn==0.11.2
  - shap==0.40.0
