name: Python Linting
on:
  push:
    branches: [master, dockerisation]
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "dockerisation"
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: monenv
          environment-file: environment.yml
          python-version: '3.10'
          auto-activate-base: false
      - name: Test conda environment 
        shell: bash
        run: |
          conda info
          conda list
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --max-complexity=10 --max-line-length=79 --statistics
      - name: Lint with Pylint
        run: |
          pip install pylint
          pylint src
